### ISSUE TITLE
I don't seems getting it to work, not the windows app at least

### ISSUE THREAD

**Issue by Ziv89** [Wouterdek/magic4pc#1]
I tried to enable Dev mode and running the bat file.. the app doesn't launch  on windows 10.

It does work on my LG c1 though, but I need to run the client on my PC..

is there more proper guide how to install it on windows 10? thanks.

**Comment by Wouterdek** [comment]
Hi there! I've uploaded [a new version](https://github.com/Wouterdek/magic4pc/releases/tag/1.0.1) of the windows app which should (hopefully) fix your installation problems.
Let me know if it doesn't work.
