### ISSUE TITLE
i cant install this.

### ISSUE THREAD

**Issue by usernoobguy** [Wouterdek/magic4pc#11]
Dear developer, im very appreciate you made this tool, i really want to use my LG TV remote to controll my pc, but i cant install it as well,  the system show those things i cant understand, im a noob at this, pls help th
![擷取](https://user-images.githubusercontent.com/99551629/153720201-2972ac74-006e-404d-9e6c-fb6be4563d5a.PNG)
![擷取 PNG2](https://user-images.githubusercontent.com/99551629/153720203-4eb9ab6f-d132-4687-bcd0-dd0785d8a737.PNG)
x

**Comment by Wouterdek** [comment]
Unfortunately, as I cannot read Chinese, I cannot read these error messages.

Try downloading [this zip file](https://download.microsoft.com/download/7/4/1/7411b780-569f-4d46-b332-5a5619127239/Microsoft.WindowsAppRuntime.Redist.1.0.0.zip) and installing "WindowsAppSDK-Installer-x86/WindowsAppRuntimeInstall.exe".

**Comment by usernoobguy** [comment]
> 

Hi Wouterdek, thx for answering my question.
i tried to install the zip file you provided, here is other error message, i google it but still don't know how to debug this problem, my developer mode is enable, sysytem : win10 LTSC 2019
![error](https://user-images.githubusercontent.com/99551629/154790907-505bf772-f937-4cd1-9f0c-caed43bd79f8.jpg)

**Comment by Wouterdek** [comment]
This last screenshot indicates that the installation of WindowsAppRuntime was successful. 
Now try installing Magic4PC again by running install_x64.bat in the [latest release](https://github.com/Wouterdek/magic4pc/releases/download/1.0.1/win_install.zip).

I have not tested this app with Windows LTSC. The app may be incompatible. Also, [check](https://support.microsoft.com/en-us/topic/determine-whether-your-computer-is-running-a-32-bit-version-or-64-bit-version-of-the-windows-operating-system-1b03ca69-ac5e-4b04-827b-c0c47145944b) if you are running 32-bit (x86) or 64-bit (x64) Windows.

**Comment by usernoobguy** [comment]
![未命名](https://user-images.githubusercontent.com/99551629/155000261-a9c870f9-6167-47c9-962c-128ec8a26ee3.jpg)
lame ;c 
information shows i need install vclibs, version least tha 14.0.30035, but its hard to find out download link, so sad (sigh)

**Comment by Wouterdek** [comment]
[This page](https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge) seems to have redistributable packages for vclibs. Perhaps [this one](https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx) is what you need?

**Comment by usernoobguy** [comment]
@Wouterdek
Hey Wouterdek, sorry i'm busy for past day. I tried to reinstall win 10 and download the tool again, here you can see the picture
![未命名](https://user-images.githubusercontent.com/99551629/166098831-a076219f-4180-4d55-b5f6-15ae37b41c3c.png)
, idk its successfully installed or not, and tv root tool you provied seems gone(https://github.com/Wouterdek/magic4pc/blob/master/rootmy.tv), really hope i can use it soon ! much love !

Tom.

**Comment by usernoobguy** [comment]
its installed :D
