### ISSUE TITLE
Cant open application after instalation

### ISSUE THREAD

**Issue by kSzajo** [Wouterdek/magic4pc#12]
I turned on developer mode on tv and installed magic4pc via WindowsAppRuntimeInstall.exe. I had to run as root. 

Whats next? I dont see any new installed app

**Comment by Informatic** [comment]
~~You need to install the companion webOS application:
https://github.com/Wouterdek/magic4pc/releases/tag/1.0.1~~

~~For that you need to either [Root Your TV](https://rootmy.tv) or figure out webOS Developer Mode (downside of that solution is that it gets reset every 50 hours)~~

~~Whenever you get that, you can either use: https://github.com/webosbrew/dev-manager-desktop or manually over SSH/telnet via one of the relevant commands here: https://www.webosbrew.org/pages/commands-cheatsheet.html~~

↓ sorry, I am very tired... :man_facepalming:

**Comment by Wouterdek** [comment]
To install the windows app, run `install_x64.bat`, not `WindowsAppRuntimeInstall.exe`.
