### ISSUE TITLE
After TV rooted, I'm stuck at this part.

### ISSUE THREAD

**Issue by usernoobguy** [Wouterdek/magic4pc#17]
![未命名](https://user-images.githubusercontent.com/99551629/167386370-0b47d9ff-11bc-4db9-b564-15c4fa82724e.png)
I'm already turn on ssh server from homebrew channel app, following guide to install but its not working.

**Comment by Wouterdek** [comment]
Enter the full path to the ipk file (which is in the download). So if the ipk file is at `C:\Users\user1\Downloads\me.wouterdek.magic4pc_1.0.0_all.ipk`, then you should run the command `ares-install --device LGTV C:\Users\user1\Downloads\me.wouterdek.magic4pc_1.0.0_all.ipk`

**Comment by usernoobguy** [comment]
Hey @Wouterdek thx for reply,
It seems my network setting incorrect，I’m not sure which part is wrong.
![3B6F117E-CF90-4535-9DF9-876591A139F8](https://user-images.githubusercontent.com/99551629/167615267-9bc5680f-0030-4f25-8ce8-693c65bffb81.jpeg)
![717852BF-0B41-482B-A173-824F67CE1503](https://user-images.githubusercontent.com/99551629/167615293-6d23679d-119c-4984-acaa-331b21f1c400.jpeg)
![FB996DB6-5BCF-4549-9CFA-70B7D5847AB2](https://user-images.githubusercontent.com/99551629/167615320-c2d779cf-cdf8-4eb0-912f-a899fe626653.jpeg)

**Comment by usernoobguy** [comment]
![DCA901CB-7238-445F-8488-0F89688D7A31](https://user-images.githubusercontent.com/99551629/167615668-8309ae77-cff9-42af-a4aa-44232a822458.jpeg)
I took IP Dress from here, I don’t know my device port, so I set “22” by default

**Comment by usernoobguy** [comment]
> Enter the full path to the ipk file (which is in the download). So if the ipk file is at `C:\Users\user1\Downloads\me.wouterdek.magic4pc_1.0.0_all.ipk`, then you should run the command `ares-install --device LGTV C:\Users\user1\Downloads\me.wouterdek.magic4pc_1.0.0_all.ipk`

Update: app is installed ! But pc won’t scan out tv even they are at same internet.
Magic4pc in tv black screen.

**Comment by usernoobguy** [comment]
i have other problem
