### ISSUE TITLE
License, packaging

### ISSUE THREAD

**Issue by Informatic** [Wouterdek/magic4pc#2]
Hello!
This seems like a great project. A couple of quick questions.

1. I don't see any license stated, except for `package.json` (MIT) in webOS app part. What is the license of this project?

2. Would you be willing to merge in some minor fix PRs? My TV runs webOS 3.x and TV application seems to fail to launch. I can sit down and adjust build configuration and fix any bugs that I were to find.

3. [webosbrew](https://webosbrew.org) (that I am part of) maintains [a repository of unofficial webOS apps](https://repo.webosbrew.org) - would you mind if we published Your application there?
Currently distribution is based on links to "manifest files" that are (mostly) included in github releases, alongside `ipk` files, like here for example: https://github.com/mariotaku/moonlight-tv/releases/tag/v1.2.7 ([manifest schema](https://github.com/webosbrew/docs/blob/main/schemas/HomebrewPackageManifest.schema.json), [apps repository](https://github.com/webosbrew/apps-repo), [final static site](https://repo.webosbrew.org/))
I can set up full CI flow to automatically build webOS-side application and generate relevant manifest when pushing a tag into the repo, to reduce any effort on You. Example CI setup we have in one of the projects: https://github.com/webosbrew/youtube-webos/blob/main/.github/workflows/release.yml

**Comment by Wouterdek** [comment]
Hi!

>     1. What is the license of this project?

It's all MIT licensed.

>     2. Would you be willing to merge in some minor fix PRs? My TV runs webOS 3.x and TV application seems to fail to launch. I can sit down and adjust build configuration and fix any bugs that I were to find.

Sure, if you create a PR I'll take a look.

>     3. [webosbrew](https://webosbrew.org) (that I am part of) maintains [a repository of unofficial webOS apps](https://repo.webosbrew.org) - would you mind if we published Your application there?
>        Currently distribution is based on links to "manifest files" that are (mostly) included in github releases, alongside `ipk` files, like here for example: https://github.com/mariotaku/moonlight-tv/releases/tag/v1.2.7 ([manifest schema](https://github.com/webosbrew/docs/blob/main/schemas/HomebrewPackageManifest.schema.json), [apps repository](https://github.com/webosbrew/apps-repo), [final static site](https://repo.webosbrew.org/))
>        I can set up full CI flow to automatically build webOS-side application and generate relevant manifest when pushing a tag into the repo, to reduce any effort on You. Example CI setup we have in one of the projects: https://github.com/webosbrew/youtube-webos/blob/main/.github/workflows/release.yml

Go ahead, the project looks very interesting. I've not been able to root my TV, but if I do a third-party package manager sounds very useful.

**Comment by Informatic** [comment]
1. Thanks.
2. Great, I'll file a PR for compatibilty fix, and a bunch of TODO-issues (I am willing to finish, just want a place to track it in) of the things I thought of after a quick look after making an app run on my TV (before testing actual windows agent yet)
3. If you were unable to root your TV due to it being already patched, I've got a good news for you - expect a new release in the following week that should work with all current firmware versions.
