### ISSUE TITLE
How can I install this app via SSH from TV shell?

### ISSUE THREAD

**Issue by stiw47** [Wouterdek/magic4pc#22]
Hi! Not an actual issue, but I don't know where else would ask. My apologize if this is not the proper place, and please be free to close it immediately.

Model: LG OLED55C11LB
WebOS version: 6.2.0-35 (kisscurl-kavir)
System version: 3.21.20
Rooted with https://rootmy.tv/

I have a hard time to connect with TV either from SDK or from dev-manager-desktop. 
`ares-install C:\Users\stiw4\Desktop\me.wouterdek.magic4pc_1.0.0_all.ipk` is givving `ares-install ERR! Error: All configured authentication methods failed` and there is similar behavior with dev-manager-desktop:

![image](https://user-images.githubusercontent.com/3337416/193208459-1d05d5c1-c8fc-4b75-bf22-c6b73a98bd48.png)

![image](https://user-images.githubusercontent.com/3337416/193208492-05741c77-67fa-4e23-b27f-7c509d489398.png)

I rooted my TV, as already said, and I'm using ssh key, not using password. I believe that problem is that I have no idea what "Private Key Name" should be, where key should be stored and what ever else. Just for note, this is the right key which I'm using every day to login to same this TV via SSH from MobaXterm.

So since I already have root SSH access, I would like to skip this ares-install thing and to install your .ipk by executing command directly on TV. I already have your `me.wouterdek.magic4pc_1.0.0_all.ipk` file in my `/tmp` folder on TV, but I don't know what would be right `luna-send` command, if this is possible at all. 

I read [here](http://45.140.167.171/ipk/), and I already tried with:

`luna-send -i -f luna://com.webos.appInstallService/install '{"id":"me.wouterdek.magic4pc", "ipkUrl":"/tmp/me.wouterdek.magic4pc_1.0.0_all.ipk", "subscribe":true}' &`

But this returned me following output:

```
root@LGwebOSTV:/tmp# {
    "subscribed": true,
    "returnValue": true
}
{
    "id": "me.wouterdek.magic4pc",
    "statusValue": 262,
    "details": {
        "packageId": "",
        "receivedSize": "0",
        "modifiedTime": "",
        "unpackFileSize": "0",
        "client": "com.webos.lunasend-6752",
        "id": "me.wouterdek.magic4pc",
        "subscribe": true,
        "totalSize": "0",
        "verified": true,
        "installBasePath": "/media/cryptofs",
        "silence": true,
        "downgrade": false,
        "paused": false,
        "permissionLevel": "",
        "simpleStatus": "download",
        "pkgType": "",
        "ipkUrl": "/tmp/me.wouterdek.magic4pc_1.0.0_all.ipk",
        "update": false,
        "ipkFile": ""
    }
}
{
    "id": "me.wouterdek.magic4pc",
    "statusValue": 263,
    "details": {
        "packageId": "",
        "receivedSize": "0",
        "modifiedTime": "",
        "unpackFileSize": "0",
        "client": "com.webos.lunasend-6752",
        "id": "me.wouterdek.magic4pc",
        "subscribe": true,
        "totalSize": "0",
        "verified": true,
        "installBasePath": "/media/cryptofs",
        "silence": true,
        "downgrade": false,
        "paused": false,
        "permissionLevel": "",
        "simpleStatus": "download",
        "pkgType": "",
        "ipkUrl": "/tmp/me.wouterdek.magic4pc_1.0.0_all.ipk",
        "update": false,
        "ipkFile": ""
    }
}
{
    "id": "me.wouterdek.magic4pc",
    "statusValue": 23,
    "details": {
        "packageId": "",
        "receivedSize": "0",
        "modifiedTime": "",
        "unpackFileSize": "0",
        "client": "com.webos.lunasend-6752",
        "id": "me.wouterdek.magic4pc",
        "subscribe": true,
        "totalSize": "0",
        "verified": true,
        "errorCode": -4,
        "installBasePath": "/media/cryptofs",
        "silence": true,
        "reason": "app/install failed Server error: [A.001.01 Wrong App ID] appFile is missing",
        "downgrade": false,
        "paused": false,
        "permissionLevel": "",
        "simpleStatus": "download",
        "state": "download failed",
        "pkgType": "",
        "ipkUrl": "/tmp/me.wouterdek.magic4pc_1.0.0_all.ipk",
        "update": false,
        "ipkFile": ""
    }
}
```

And application didn't install.
I am familiar with Linux, but this is different world. On top, I read that there are some write-protected partitions, which shouldn't be touched, and I don't know which ones, so I don't want to experiment further more, cause this is not cheap toy 😁

Is there some `luna-send` command which can install .ipk directly from TV shell?
Many thanks upfront.

**Comment by Informatic** [comment]
You need to use "/dev/install" Luna endpoint for installation - see
relevant snippet here:
https://www.webosbrew.org/pages/commands-cheatsheet.html

In regards to dev-manager-desktop - I'd recommend dropping an issue in
their GitHub repo about this - this likely comes from the fact that it
expects the key name to be a path relative to .ssh directory, same as
ares-install and friends do - we could probably patch it up to fix this
when specifying an explicit key path at some point...

**Comment by stiw47** [comment]
Thanks a lot @Informatic . Anyway, I managed to find right command in mean time, then came here to close the issue and found that I have an answer.

Command which worked for me, copy/pasted from [webos-homebrew-channel](https://github.com/webosbrew/webos-homebrew-channel/blob/main/README.md#manual), was same command they recommending for manual install of Homebrew (modified below with my parameters):

`luna-send-pub -i 'luna://com.webos.appInstallService/dev/install' '{"id":"me.wouterdek.magic4pc","ipkUrl":"/tmp/me.wouterdek.magic4pc_1.0.0_all.ipk","subscribe":true}'`

I will raise the issue for sure at dev-manager-desktop, thanks once again.
