### ISSUE TITLE
Linux client; network protocol documentation?

### ISSUE THREAD

**Issue by rotdrop** [Wouterdek/magic4pc#24]
Hi,

thank you for this app. Actually, I was thinking of something like this and now just stumbled over it in Discord.

Do you have any documentation about the network protocol/data packages s.t. it would be possible to implement a "receiver" (= app on your pc) for other operating systems?

Thanks.

**Comment by Informatic** [comment]
There's an alternative Linux/Golang-based receiver here: https://github.com/mafredri/magic4linux

**Comment by rotdrop** [comment]
Thanks! :)

**Comment by rotdrop** [comment]
Closing. Works so far using magic4linux.
