### ISSUE TITLE
Turn of TV pointer? How to terminate the app?

### ISSUE THREAD

**Issue by rotdrop** [Wouterdek/magic4pc#25]
Hi, thanks again for your app!

It is working so far (with magic4linux as client). It is a little bit inconvenient that the native cursor of the TV is always present in addition to the mouse cursor of the PC. I fear that this is a limitation of the WebOS? Or is it possible to turn the pointer off and just have the mouse cursor of the PC on the screen?

Then:  how do I terminate the app?

Thank you!

**Comment by parkerlreed** [comment]
Long hold Back to exit the application TV side. 

Would also love a way to hide the TV cursor.

**Comment by rotdrop** [comment]
Perhaps another idea: if it is not possible to hide the TV-cursor, how about to synchronize the position of the mouse-cursor with the TV-cursor? At least with magic4linux the two cursors are not at the same position.

Is this a problem or feature of the magic4linux app, or does this also happen with the Windows app contained in magic4pc?

What disturbs me most is that the TV cursor is much more prominent than the computer's mouse cursor. If both were at the same position, this would already be an improvement over visually being confronted with two different cursors. I have then to "concentrate" to pick the right one.

**Comment by Informatic** [comment]
That is very likely a bug that needs to be patched. As far as I can tell, it's not possible to hide a cursor inside a webapp, as fas as I can tell. (though I may be wrong)

**Comment by rotdrop** [comment]
The "That is very likely a bug" refers to the point that in magic4linux the cursor positions do not coincide?

**Comment by Informatic** [comment]
It's either on magic4pc or magic4linux side. I'll play with this next week and try to debug it.

**Comment by parkerlreed** [comment]
They match fine here. Right on the very point of both. Maybe something with the desktop environment?

**Comment by rotdrop** [comment]
> They match fine here. Right on the very point of both. Maybe something with the desktop environment?

Just to make sure: you are also using this with magic4linux on a Linux Desktop?

Of course, there may be desktop settings in the way like mouse acceleration, a second pointer device and so on. Does magic4pc send absolute pointer positions, or just relative moves?

**Comment by rotdrop** [comment]
Ok, I had mouse acceleration at 2x. Disabling the acceleration make both pointer move with the same speed. Looking at the source code of magic4linux I had the impression that it tries to set the absolute  mouse position. But that's something do discuss there, not here. I am closing this issue now as resolved:

- the mouse cursor of the TV cannot probably not be turned off
- the app seems to send the correct coordinates.
- my question about turning the app off has been answered
